source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'BlinkingLabel_Example' do
  pod 'BlinkingLabel', :path => '../'

  target 'BlinkingLabel_Tests' do
    inherit! :search_paths

    
  end
end
